name: Build ESP32-S3 Only

on:
  push:
    branches: [ mega ]
  pull_request:
    branches: [ mega ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build for ESP32-S3
      run: pio run -e normal_ESP32s3_4M316k  # Poprawiony env z listy

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: espeasy-s3-bin
        path: .pio/build/normal_ESP32s3_4M316k/*.bin
